# -*- coding: utf-8 -*-
"""Password_generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1jJwnJ2-LYRGhnZdj5ylSjZXDV-VABj

#Lógica

Para podermos começar a programar devemos entender a lógica de um gerador de senhas. O que é preciso para ter uma senha forte?
- 8 Dígitos (min)
- Caracteres especiais (1 min)
- Números (min 2)
- Letras Maiúsculas (min 1)
- Letras minúsculas

#Programa
É necessário entender como o programa vai funcionar, então, o que é preciso pra isso?
-Uma mensagem poder iniciar o programa
-Geração da senha
-Apresentação da senha
"""

import random
import string

def generate_password(length=12, use_uppercase=True, use_lowercase=True, use_digits=True, use_specials=True):
    # Build the character set based on the selected options
    characters = ''
    if use_uppercase:
        characters += string.ascii_uppercase
    if use_lowercase:
        characters += string.ascii_lowercase
    if use_digits:
        characters += string.digits
    if use_specials:
        characters += string.punctuation

    # Check if at least one type of character has been selected
    if not characters:
        raise ValueError("At least one type of character must be selected to generate the password.")

    # Generate the random password
    password = ''.join(random.choice(characters) for _ in range(length))
    return password

def main():
    print("Welcome to the Password Generator!\nWould you like to create a new password? \n")

    while True:
        try:
            choice = int(input("1-Yes | 2-No: \n"))
            if choice in [1, 2]:
                break
            else:
                print("Invalid choice, please enter 1 for Yes or 2 for No.")
        except ValueError:
            print("Invalid input. Please enter a number (1 or 2).")

    if choice == 2:
        print("It's a pity that we can't help you =(")
        return  # Exit the function if the user does not want to generate a password

    if choice == 1:
        print("Let's generate a new password!")

        while True:
            try:
                length = int(input("Enter the desired password length (positive integer): \n"))
                if length > 0:
                    break
                else:
                    print("Please enter a positive integer for the password length.")
            except ValueError:
                print("Invalid input. Please enter a positive integer.")

        # Input validation for uppercase letters
        while True:
            use_uppercase = input("Include uppercase letters?\n 1-Yes | 2-No: \n").lower()
            if use_uppercase in ['1', '2']:
                use_uppercase = (use_uppercase == '1')
                break
            else:
                print("Invalid input. Please enter '1' for yes or '2' for no.")

        # Input validation for lowercase letters
        while True:
            use_lowercase = input("Include lowercase letters?\n 1-Yes | 2-No: \n")
            if use_lowercase in ['1', '2']:
                use_lowercase = (use_lowercase == '1')
                break
            else:
                print("Invalid input. Please enter '1' for yes or '2' for no.")

        # Input validation for digits
        while True:
            use_digits = input("Include digits?\n 1-Yes | 2-No: \n")
            if use_digits in ['1', '2']:
                use_digits = (use_digits == '1')
                break
            else:
                print("Invalid input. Please enter '1' for yes or '2' for no.")

        # Input validation for special characters
        while True:
            use_specials = input("Include special characters?\n 1-Yes | 2-No: \n").lower()
            if use_specials in ['1', '2']:
                use_specials = (use_specials == '1')
                break
            else:
                print("Invalid input. Please enter '1' for yes or '2' for no.")

        # Check if at least one type of character has been selected
        while not (use_uppercase or use_lowercase or use_digits or use_specials):
            print("You must select at least one type of character for your password.")
            # Repeat the prompts for character types
            use_uppercase = input("Include uppercase letters? \n1 -Yes | 2-No: \n") == '1'
            use_lowercase = input("Include lowercase letters? \n1 -Yes | 2-No: \n") == '1'
            use_digits = input("Include digits? \n 1-Yes | 2-No: \n") == '1'
            use_specials = input("Include special characters? \n 1-Yes | 2-No: \n") == '1'

        password = generate_password(length, use_uppercase, use_lowercase, use_digits, use_specials)
        print(f"Your generated password is: \n {password}")

        name = input("Enter a name for this password: \n")

        print("Save it somewhere so don't lose it")
if __name__ == "__main__":1

    main()